# Generated by Django 6.0.3 on 2026-03-11 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999".Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
