# Generated by Django 6.0.3 on 2026-03-11 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_adress', to='user.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
