# Generated by Django 6.0.3 on 2026-03-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='utype',
            field=models.CharField(blank=True, choices=[('c', 'Customer'), ('r', 'Restaurant'), ('d', 'Driver')], default='c', help_text='User Type', max_length=1),
        ),
    ]
