# Generated by Django 6.0.3 on 2026-03-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='total_orders',
        ),
        migrations.AddField(
            model_name='address',
            name='adrname',
            field=models.CharField(default='home', help_text='Short name to identify the adress', max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(help_text='Your full address'),
        ),
    ]
