# Generated by Django 6.0.3 on 2026-03-16 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_customerprofile_total_orders_address_adrname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='uprice',
            field=models.DecimalField(decimal_places=2, default=None, help_text='snapshot of item price at order time', max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='default_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='saved_adresses_for_user', to='user.address'),
        ),
    ]
