# Generated by Django 6.0.3 on 2026-03-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_orderitem_uprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrauntmodel',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='restrauntmodel',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
