# Generated by Django 6.0.3 on 2026-03-16 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_restrauntmodel_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='default_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saved_adresses_for_user', to='user.address'),
        ),
    ]
