# Generated by Django 6.0.3 on 2026-03-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_customerprofile_default_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='total_deliveries',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
