# Generated by Django 6.0.3 on 2026-03-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_driverprofile_total_deliveries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('IsOwnerOrReadOnly', 'AA owner can edit/delete, others read-only'), ('IsRestaurantOwner', 'AA only restaurant owner can edit restaurant and menu items'), ('IsCustomer', 'AA only customers can place orders and write reviews'), ('IsDriver', 'AA only drivers can update delivery status and location'), ('IsOrderCustomer', 'AA only order customer can view order details'), ('IsRestaurantOwnerOrDriver', 'AA restaurant owner or assigned driver can update order status')]},
        ),
    ]
