# Generated by Django 6.0.3 on 2026-03-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrauntmodel',
            name='total_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
