# Generated by Django 6.0.3 on 2026-03-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_restrauntmodel_total_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='default_address',
        ),
    ]
