# Generated by Django 6.0.3 on 2026-03-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_order_actual_delivery_time_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adratorder',
            field=models.TextField(default='some adress'),
            preserve_default=False,
        ),
    ]
