# Generated by Django 6.0.3 on 2026-03-26 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_order_adratorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='utype',
            field=models.CharField(blank=True, choices=[('c', 'Customer'), ('r', 'Restaurant Owner'), ('d', 'Delivery Driver   ')], default='c', help_text='User Type', max_length=1),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
