# Generated by Django 6.0.3 on 2026-03-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_customuser_utype_alter_driverprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
