# Generated by Django 6.0.3 on 2026-03-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_driverprofile_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
