# Generated by Django 6.0.3 on 2026-03-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_driverprofile_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrauntmodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
