# Generated by Django 6.0.3 on 2026-04-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_restrauntmodel_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='item_image',
            new_name='foodimage',
        ),
    ]
