# Generated by Django 6.0.3 on 2026-04-03 04:46

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_rename_item_image_menuitem_foodimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='coordinates for distance calculation', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restrauntmodel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of restaurant', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restrauntmodel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='GPS coordinates for distance calculation', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='restrauntmodel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of restaurant', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
